package ru.itis.tripbook.model.enums;


public enum CarBrand {
    ACURA("Acura"),
    ADLER("Adler"),
    ALFA_ROMEO("Alfa Romeo"),
    AUDI("Audi"),
    BMW("BMW"),
    BYD("BYD"),
    BENTLEY("Bentley"),
    BRILLIANCE("Brilliance"),
    BUICK("Buick"),
    CHERYEXEED("CHERYEXEED"),
    CADILLAC("Cadillac"),
    CHANGAN("Changan"),
    CHERY("Chery"),
    CHEVROLET("Chevrolet"),
    CRYSLER("Chrysler"),
    CITROEN("Citroen"),
    DS("DS"),
    DACIA("Dacia"),
    DAEWOO("Daewoo"),
    DIHATSU("Daihatsu"),
    DATSUN("Datsun"),
    DERWAYS("Derways"),
    DODGE("Dodge"),
    DODGE_FENG("DongFeng"),
    DONIVEST("Doninvest"),
    FAW("FAW"),
    FIAT("Fiat"),
    FORD("Ford"),
    GMC("GMC"),
    GEELY("Geely"),
    GENESIS("Genesis"),
    GREAT_WALL("Great Wall"),
    HAFEI("Hafei"),
    HAIMA("Haima"),
    HAVAL("Haval"),
    HONDA("Honda"),
    HUMMER("Hummer"),
    HYUNDAI("Hyindai"),
    INFINITY("Infiniti"),
    IRAN_KHODRO("Iran Khodro"),
    ISUZU("Isuzu"),
    JAC("JAC"),
    JAGUAR("Jaguar"),
    JEEP("Jeep"),
    KIA("Kia"),
    LADA("LADA(ВАЗ)"),
    LAMBORGHINI("Lamborghini"),
    LANCIA("Lancia"),
    LAND_ROVER("Land Rover"),
    LEXUS("Lexus"),
    LIFAN("Lifan"),
    LICOLN("Lincoln"),
    LUXGEN("Luxgen"),
    MINI("MINI"),
    MAZDA("Mazda"),
    MERCEDES_BENZ("Mercedes-Benz"),
    MERCURY("Mercury"),
    MITSUBISHI("Mitsubishi"),
    NISSAN("Nissan"),
    OPEL("Opel"),
    PUCH("PUCH"),
    PEUGEOT("Peugeot"),
    PONTIAC("Pontiac"),
    PORSCHE("Porsche"),
    PROTON("Proton"),
    RAVON("Ravon"),
    RENAULT("Renault"),
    ROVER("Rover"),
    SEAT("SEAT"),
    SAAB("Saab"),
    SATURN("Saturn"),
    SCION("Scion"),
    SHUANG_HUAN("ShuangHuan"),
    SKODA("Skoda"),
    SMART("Smart"),
    SSANG_YONG("SsangYong"),
    SUBARU("Subaru"),
    SUZUKI("Suzuki"),
    TESLA("Tesla"),
    TIANMA("Tianma"),
    TIANYE("Tianye"),
    TOYOTA("Toyota"),
    VOLKSWAGEN("Volkswagen"),
    VOLVO("Volvo"),
    VORTEX("Vortex"),
    ZX("ZX"),
    ZOTYE("Zotye"),
    GAZ("Газ"),
    ZAZ("ЗАЗ"),
    IZH("ИЖ"),
    LUAS("ЛуАЗ"),
    MOSKVICH("Москвич"),
    SMZ("СМЗ"),
    TAGAS("ТагАЗ"),
    UAZ("УАЗ");
//    AC,
//    AM General,
//    AMC,
//            Alpina,
//    Alpine,
//            Apal,
//    Ariel,
//            Aro,
//    Asia,
//    Aston Martin,
//    Auburn,
//            Aurus,
//    Austin,
//    Austin Healey,
//    Autobianchi,
//            BAIC,
//    Bajaj,
//    Baltijas Dzips,
//    Batmobile,
//            Bertone,
//    Bilenkin,
//    Bio auto,
//    Bitter,
//            Borgward,
//    Brabus,
//            Bristol,
//    Bufori,
//            Bugatti,
//    Byvin,
//            Callaway,
//    Carbodies
//            Caterham
//    Chana,
//            ChangFeng,
//    Changhe,
//            Cizeta,
//    Coggiola,
//            Cord,
//    Cupra,
//            DKW,
//    DW Hower,
//    Dadi,
//            Daimler,
//    Dallara,
//    De Tomaso,
//    DeLorean,
//            DeSoto,
//    Deco Rides,
//    Delage,
//            Donkervoort,
//    E-Car,
//            Eagle,
//    Eagle Cars,
//    Excalibur,
//            FSO,
//    Ferrari,
//            Fisker,
//    Flanker,
//            Foton,
//    Fuqi,
//            GAC,
//    GP,
//            Geo,
//    Gonow,
//            Gordon,
//    Hanomag,
//            Hawtai,
//    Heinkel,
//            Hennessey,
//    Hindustan,
//    Hispano-Suiza,
//            Holden,
//    Horch,
//            HuangHai,
//    Hudson,
//            IVECO,
//    Innocenti,
//            International,
//    Invicta,
//            Isdera,
//    JMC,
//            Jensen,
//    Jinbei,
//    KTM AG,
//    Koenigsegg,
//            LTI,
//    Landwind,
//            LiXiang,
//    Liebao Motor,
//    Ligier,
//            Logem,
//    Lotus,
//            Lucid,
//    MG,
//            Mahindra,
//    Marcos,
//            Marlin,
//    Marussia,
//            Maruti,
//    Maserati,
//            Maybach,
//    McLaren,
//            Mega,
//    Metrocab,
//            Microcar,
//    Minelli,
//            Mitsuoka,
//    Morgan,
//            Morris,
//    Nash,
//            Nio,
//    Noble,
//            Oldsmobile,
//    Osca,
//            PGO,
//    Packard,
//            Pagani,
//    Panoz,
//            Perodua,
//    Piaggio,
//            Plymouth,
//    Polestar,
//            Premier,
//    Puma,
//            Qoros,
//    Qvale,
//            RAM,
//    Rambler,
//            Reliant,
//    Renaissance,
//    Renault Samsung,
//    Rezvani,
//            Rimac,
//    Rinspeed,
//            Roewe,
//    Rolls-Royce,
//            Ronart,
//    Saipa,
//            Saleen,
//    Santana,
//            Sears,
//    Shanghai Maple,
//    Simca,
//            Soueast,
//    Spectre,
//            Spyker,
//    Steyr,
//            Studebaker,
//    TATA,
//            TVR,
//    Talbot,
//            Tatra,
//    Tazzari,
//            Think,
//    Tofas,
//            Trabant,
//    Tramontana,
//            Triumph,
//    Ultima,
//            Vauxhall,
//    Vector,
//            Venturi,
//    W Motors,
//    Wanderer,
//            Wartburg,
//    Weltmeister,
//            ("Westfield"),
//    ("Wiesmann"),
//            ("Willys"),
//    ("Xin Kai"),
//    ("Xpeng"),
//            ("Yulon"),
//    ("Zastava"),
//            ("Zenos"),
//    ("Zenvo"),
//            ("Zibar"),
//    ("Ё-мобиль"),
//            ("Автокам"),
//    ("ЗИЛ"),
//            ("ЗиС"),
//    ("Канонир"),
//            ("Комбат"),
//    ("Спортивные авто и Реплики");

    private String name;

    CarBrand(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
